import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'Desarrollo Android de inexperto a Experto',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Principiante',
  },
  {
    id: 2,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'UI/UX Complete Guide',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermedio',
  },
  {
    id: 3,
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'Dominio de los fundamentos del modelado de datos',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Principante',
  },
  {
    id: 4,
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'La guía completa de Docker y Kubernetes',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermedio',
  },
  {
    id: 5,
    cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
    title: 'React moderno con MUI y Redux',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermedio',
  },
  {
    id: 6,
    cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
    title: 'Curso acelerado de hacking ético de cero a maestría',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Princitante',
  },
  {
    id: 7,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Adobe Lightroom Para Principiantes: Edición fotográfica completa',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Principiante',
  },
]
